CREATE TABLE OFFERTE_ANALISI (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_ANAGRAFICA BIGINT,
    CODICE_FISCALE VARCHAR(255),
    PARTITA_IVA VARCHAR(255),
    CODICE_EER_CER VARCHAR(255),
    DESCRIZIONE_RIFIUTI VARCHAR(255),
    VALIDITA_OFFERTA DATE,
    CONDIZIONI_DI_PAGAMENTO VARCHAR(255),
    ANALISI_DI_CLASSIFCAZIONE VARCHAR(255),
    DATA_FIRMA DATE,
    FIRMA_DIGITALE VARCHAR(255),
    DATA_INSERIMENTO DATE,
    FOREIGN KEY (ID_ANAGRAFICA) REFERENCES ANAGRAFICHE(ID)
);

INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, ANALISI_DI_CLASSIFCAZIONE, DATA_FIRMA, FIRMA_DIGITALE, DATA_INSERIMENTO)
VALUES (1, 'ABC123', '123456789', 'EER123', 'Waste Description 1', '2024-03-05', 'Payment Condition 1', 'Classification Analysis 1', '2024-03-05', 'Digital Signature 1', '2024-03-05');

INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, ANALISI_DI_CLASSIFCAZIONE, DATA_FIRMA, FIRMA_DIGITALE, DATA_INSERIMENTO)
VALUES (2, 'DEF456', '987654321', 'EER456', 'Waste Description 2', '2024-03-06', 'Payment Condition 2', 'Classification Analysis 2', '2024-03-06', 'Digital Signature 2', '2024-03-06');

INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, ANALISI_DI_CLASSIFCAZIONE, DATA_FIRMA, FIRMA_DIGITALE, DATA_INSERIMENTO)
VALUES (3, 'GHI789', '192837465', 'EER789', 'Waste Description 3', '2024-03-07', 'Payment Condition 3', 'Classification Analysis 3', '2024-03-07', 'Digital Signature 3', '2024-03-07');

