CREATE TABLE OFFERTE_ANALISI (
    ID INT AUTO_INCREMENT,
    ID_ANAGRAFICA INT,
    CODICE_FISCALE VARCHAR(255),
    PARTITA_IVA VARCHAR(255),
    CODICE_EER_CER VARCHAR(255),
    DESCRIZIONE_RIFIUTI VARCHAR(255),
    VALIDITA_OFFERTA DATE,
    CONDIZIONI_DI_PAGAMENTO VARCHAR(255),
    ANALISI_DI_CLASSIFCAZIONE VARCHAR(255),
    DATA_FIRMA DATE,
    FIRMA_DIGITALE VARCHAR(255),
    DATA_INSERIMENTO DATE,
    PRIMARY KEY (ID)
);

INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE) VALUES (1, 'CF1');
INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE) VALUES (2, 'CF2');
INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE) VALUES (3, 'CF3');
