CREATE TABLE OFFERTA_SMALTIMENTO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_ANAGRAFICA BIGINT,
    CODICE_FISCALE VARCHAR(255),
    DATA_INSERIMENTO DATE,
    PARTITA_IVA VARCHAR(255),
    CODICE_EER_CER VARCHAR(255),
    DESCRIZIONE_RIFIUTI VARCHAR(255),
    SMALTIMENTO VARCHAR(255),
    TRASPORTO_CON_MOTRICE VARCHAR(255),
    TRASPORTO_CON_AUTOTRENO_BILICO VARCHAR(255),
    EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO VARCHAR(255),
    QUOATA_MINIMA_FATTURABILE_FORMULARIO VARCHAR(255),
    COMPILAZIONE_GESTIONE_FORMULARIO VARCHAR(255),
    ANALISI_DI_CLASSIFICAZIONE VARCHAR(255),
    VALIDITA_OFFERTA DATETIME,
    CONDIZIONI_DI_PAGAMENTO VARCHAR(255),
    DATA_FIRMA DATETIME,
    FIRMA_DIGITALE VARCHAR(255),
    FOREIGN KEY (ID_ANAGRAFICA) REFERENCES ANAGRAFICA(ID)
);


INSERT INTO OFFERTA_SMALTIMENTO (ID, ID_ANAGRAFICA, CODICE_FISCALE, DATA_INSERIMENTO, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, SMALTIMENTO, TRASPORTO_CON_MOTRICE, TRASPORTO_CON_AUTOTRENO_BILICO, EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO, QUOATA_MINIMA_FATTURABILE_FORMULARIO, COMPILAZIONE_GESTIONE_FORMULARIO, ANALISI_DI_CLASSIFICAZIONE, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, DATA_FIRMA, FIRMA_DIGITALE) 
VALUES (1, 1, 'CF1234567890', '2024-03-05', 'PI0987654321', 'EER123', 'Rifiuto1', 'Smaltimento1', 'Motrice1', 'Autotreno1', 'ExtraSosta1', 'QuotaMinima1', 'Compilazione1', 'Analisi1', '2024-03-05 12:00:00', 'Condizioni1', '2024-03-05 12:00:00', 'Firma1');

INSERT INTO OFFERTA_SMALTIMENTO (ID, ID_ANAGRAFICA, CODICE_FISCALE, DATA_INSERIMENTO, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, SMALTIMENTO, TRASPORTO_CON_MOTRICE, TRASPORTO_CON_AUTOTRENO_BILICO, EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO, QUOATA_MINIMA_FATTURABILE_FORMULARIO, COMPILAZIONE_GESTIONE_FORMULARIO, ANALISI_DI_CLASSIFICAZIONE, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, DATA_FIRMA, FIRMA_DIGITALE) 
VALUES (2, 2, 'CF2345678901', '2024-03-06', 'PI0876543212', 'EER234', 'Rifiuto2', 'Smaltimento2', 'Motrice2', 'Autotreno2', 'ExtraSosta2', 'QuotaMinima2', 'Compilazione2', 'Analisi2', '2024-03-06 12:00:00', 'Condizioni2', '2024-03-06 12:00:00', 'Firma2');

INSERT INTO OFFERTA_SMALTIMENTO (ID, ID_ANAGRAFICA, CODICE_FISCALE, DATA_INSERIMENTO, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, SMALTIMENTO, TRASPORTO_CON_MOTRICE, TRASPORTO_CON_AUTOTRENO_BILICO, EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO, QUOATA_MINIMA_FATTURABILE_FORMULARIO, COMPILAZIONE_GESTIONE_FORMULARIO, ANALISI_DI_CLASSIFICAZIONE, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, DATA_FIRMA, FIRMA_DIGITALE) 
VALUES (3, 3, 'CF3456789012', '2024-03-07', 'PI0765432103', 'EER345', 'Rifiuto3', 'Smaltimento3', 'Motrice3', 'Autotreno3', 'ExtraSosta3', 'QuotaMinima3', 'Compilazione3', 'Analisi3', '2024-03-07 12:00:00', 'Condizioni3', '2024-03-07 12:00:00', 'Firma3');

