CREATE TABLE OFFERTE_LIQUIDO (
    ID INT AUTO_INCREMENT,
    ID_ANAGRAFICA INT,
    CODICE_FISCALE VARCHAR(255),
    PARTITA_IVA VARCHAR(255),
    CODICE_EER_CER VARCHAR(255),
    DESCRIZIONE_RIFIUTI VARCHAR(255),
    TRASPORTO_CON_MOTRICE_CISTERNA VARCHAR(255),
    TRASPORTO_CON_AUTOTRENO_BILICO VARCHAR(255),
    EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO VARCHAR(255),
    UTILIZZO_CANAL_JET VARCHAR(255),
    IMPIEGO_SECONDO_OPERATORE VARCHAR(255),
    QUOATA_MINIMA_FATTURABILE VARCHAR(255),
    COMPILAZIONE_GESTIONE_FORMULARIO VARCHAR(255),
    ANALISI_DI_OMOLOGO VARCHAR(255),
    VALIDITA_OFFERTA DATE,
    CONDIZIONI_DI_PAGAMENTO VARCHAR(255),
    ANALISI_DI_OMOLOGA VARCHAR(255),
    DATA_FIRMA DATE,
    FIRMA_DIGITALE VARCHAR(255),
    DATA_INSERIMENTO DATE,
    PRIMARY KEY (ID)
);

INSERT INTO OFFERTE_LIQUIDO (ID_ANAGRAFICA, CODICE_FISCALE) VALUES (1, 'CF1');
INSERT INTO OFFERTE_LIQUIDO (ID_ANAGRAFICA, CODICE_FISCALE) VALUES (2, 'CF2');
INSERT INTO OFFERTE_LIQUIDO (ID_ANAGRAFICA, CODICE_FISCALE) VALUES (3, 'CF3');
