CREATE TABLE OFFERTE_ANALISI (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_ANAGRAFICA BIGINT,
    CODICE_FISCALE VARCHAR(255),
    DATA_INSERIMENTO DATE,
    PARTITA_IVA VARCHAR(255),
    CODICE_EER_CER VARCHAR(255),
    DESCRIZIONE_RIFIUTI VARCHAR(255),
    SMALTIMENTO VARCHAR(255),
    TRASPORTO_CON_MOTRICE VARCHAR(255),
    TRASPORTO_CON_AUTOTRENO_BILICO VARCHAR(255),
    EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO VARCHAR(255),
    QUOATA_MINIMA_FATTURABILE_FORMULARIO VARCHAR(255),
    COMPILAZIONE_GESTIONE_FORMULARIO VARCHAR(255),
    ANALISI_DI_CLASSIFICAZIONE VARCHAR(255),
    VALIDITA_OFFERTA DATE,
    CONDIZIONI_DI_PAGAMENTO VARCHAR(255),
    DATA_FIRMA DATE,
    FIRMA_DIGITALE VARCHAR(255),
    FOREIGN KEY (ID_ANAGRAFICA) REFERENCES ANAGRAFICHE(ID)
);


INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE, DATA_INSERIMENTO, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, SMALTIMENTO, TRASPORTO_CON_MOTRICE, TRASPORTO_CON_AUTOTRENO_BILICO, EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO, QUOATA_MINIMA_FATTURABILE_FORMULARIO, COMPILAZIONE_GESTIONE_FORMULARIO, ANALISI_DI_CLASSIFCAZIONE, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, DATA_FIRMA, FIRMA_DIGITALE)
VALUES (1, 'ABC123', '2024-03-05', '123456789', 'EER123', 'Waste Description 1', 'Disposal 1', 'Transport with Tractor 1', 'Transport with Semi-trailer 1', 'Extra Stop After First Hour of Loading 1', 'Minimum Billable Quota Form 1', 'Form Management Compilation 1', 'Classification Analysis 1', '2024-03-05', 'Payment Conditions 1', '2024-03-05', 'Digital Signature 1');

INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE, DATA_INSERIMENTO, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, SMALTIMENTO, TRASPORTO_CON_MOTRICE, TRASPORTO_CON_AUTOTRENO_BILICO, EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO, QUOATA_MINIMA_FATTURABILE_FORMULARIO, COMPILAZIONE_GESTIONE_FORMULARIO, ANALISI_DI_CLASSIFCAZIONE, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, DATA_FIRMA, FIRMA_DIGITALE)
VALUES (2, 'DEF456', '2024-03-06', '987654321', 'EER456', 'Waste Description 2', 'Disposal 2', 'Transport with Tractor 2', 'Transport with Semi-trailer 2', 'Extra Stop After First Hour of Loading 2', 'Minimum Billable Quota Form 2', 'Form Management Compilation 2', 'Classification Analysis 2', '2024-03-06', 'Payment Conditions 2', '2024-03-06', 'Digital Signature 2');

INSERT INTO OFFERTE_ANALISI (ID_ANAGRAFICA, CODICE_FISCALE, DATA_INSERIMENTO, PARTITA_IVA, CODICE_EER_CER, DESCRIZIONE_RIFIUTI, SMALTIMENTO, TRASPORTO_CON_MOTRICE, TRASPORTO_CON_AUTOTRENO_BILICO, EXTRA_SOSTA_DOPO_PRIMA_ORA_CARICO, QUOATA_MINIMA_FATTURABILE_FORMULARIO, COMPILAZIONE_GESTIONE_FORMULARIO, ANALISI_DI_CLASSIFCAZIONE, VALIDITA_OFFERTA, CONDIZIONI_DI_PAGAMENTO, DATA_FIRMA, FIRMA_DIGITALE)
VALUES (3, 'GHI789', '2024-03-07', '192837465', 'EER789', 'Waste Description 3', 'Disposal 3', 'Transport with Tractor 3', 'Transport with Semi-trailer 3', 'Extra Stop After First Hour of Loading 3', 'Minimum Billable Quota Form 3', 'Form Management Compilation 3', 'Classification Analysis 3', '2024-03-07', 'Payment Conditions 3', '2024-03-07', 'Digital Signature 3');

